// Generated by CoffeeScript 1.7.1
(function() {
  var app, browserify, coffeeify, express, path, poetryChain, server, static_path;

  express = require("express");

  poetryChain = require("./poetry-chains-json");

  browserify = require('browserify-middleware');

  coffeeify = require('coffeeify');

  path = require("path");

  browserify.settings('extensions', ['.coffee']);

  browserify.settings('transform', [coffeeify]);

  browserify.settings('grep', /\.coffee$|\.js$/);

  app = express();

  app.use(require("cors")());

  app.get("/api/get-chain.json", function(request, response) {
    return poetryChain().then(function(data) {
      return response.json(data);
    });
  });

  app.get("/app", browserify("./app/index.coffee"));

  static_path = path.resolve(__dirname, "static");

  app.use("/", express["static"](static_path));

  server = app.listen(process.env.PORT || 8888, process.env.IP, function() {
    var a, p;
    a = server.address().address;
    p = server.address().port;
    return console.log("Listening to the universe at " + a + ", port " + p);
  });

}).call(this);
