// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, childProcess, path;

  childProcess = require('child_process');

  path = require("path");

  Promise = require("promise");

  module.exports = function() {
    var command, dir;
    dir = path.resolve(__dirname, "PoetryChains");
    command = "cd " + dir + "; ./run_poetry_chain.sh";
    return new Promise(function(resolve, reject) {
      return childProcess.exec(command, function(error, stdout, stderr) {
        var json;
        if (error) {
          reject(error);
        }
        json = JSON.parse(stdout);
        return resolve(json);
      });
    });
  };

}).call(this);
