// Generated by CoffeeScript 1.7.1
(function() {
  var Main, THREE;

  THREE = require("three");

  Main = (function() {
    var camera, renderer, scene, _animate;

    function Main() {}

    renderer = void 0;

    scene = void 0;

    camera = void 0;

    Main.prototype.init = function() {
      var helper, light;
      renderer = new THREE.WebGLRenderer();
      renderer.setPixelRatio(window.devicePixelRatio);
      renderer.setSize(window.innerWidth, window.innerHeight);
      renderer.setClearColor("white");
      document.body.appendChild(renderer.domElement);
      camera = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 1, 1000);
      camera.position.z = 100;
      camera.position.x = 10;
      camera.position.y = 10;
      scene = new THREE.Scene();
      light = new THREE.PointLight();
      light.position.set(200, 100, 150);
      scene.add(light);
      helper = new THREE.AxisHelper(50);
      return scene.add(helper);
    };

    _animate = function() {
      requestAnimationFrame(_animate);
      return renderer.render(scene, camera);
    };

    Main.prototype.animate = _animate;

    return Main;

  })();

  module.exports = Main;

}).call(this);
